### ISSUE TITLE
README.md links are broken

### ISSUE THREAD

**Issue by alex-bender** [uwdb/Cosette#27]
* Read Introducing Cosette --> 404
* See the Cosette Guide to see how to use Cosette --> 404 (trailing dot should be removed)

**Comment by stechu** [comment]
@alex-bender thanks for pointing out. fixed!

**Comment by LiShuMing** [comment]
`Demonstration of the Cosette Automated SQL Prover. [ paper ] SIGMOD 2017 (best demo award) ` link is broken again?
