### ISSUE TITLE
Host `cosette' looks like a remote host, `docker' can only use the local host

### ISSUE THREAD

**Issue by xuruiyang** [uwdb/Cosette#3]
I run the command:

**emacs /docker:cosette:/hott/UnivalentSemantics.v**

as exactly as being written in your README file, and got the following error:

**Host `cosette' looks like a remote host, `docker' can only use the local host**

**Comment by stechu** [comment]
@xuruiyang 
does your Emacs have `enable-remote-dir-locals` enabled?

**Comment by xuruiyang** [comment]
Of course, it does I followed your instruction exactly.

**Comment by stechu** [comment]
@xuruiyang would you want to try it again?

I believe we have fixed the problems. It can build successfully on my machine.

you might need clean it up a bit first:

eg. run `docker rm -f cosette` first and redo the build process as listed in the `readme.md`

Please let us know if it still doesn't work on your side.

**Comment by stechu** [comment]
@xuruiyang  we also updated the instructions so that you can pull the docker container from docker hub now.

**Comment by xuruiyang** [comment]
Thank you, I can pull the docker container successfully now.
